---
title: "Projekt"
author: "Jakob T Rasmussen"
date: "2025-04-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(dplyr)
library(gganimate)
```
```{r}
Kandidat <- read_csv("Data/Folketingsvalg - Kandidat.csv")
head(Kandidat)
```
```{r}
Kandidat_long <- Kandidat %>%
  pivot_longer(
    cols = -År, 
    names_to = "Parti",
    values_to = "Mandater")%>%
  filter(!is.na(Mandater)) 
```
```{r}
vline_years <- c(1973, 1977, 1984, 1994, 2001)
```

```{r}
p <- ggplot(Kandidat_long, aes(x = År, y = Mandater, color = Parti)) +
  geom_line(linewidth = 1) +
  geom_point() +
  theme_minimal() +
     geom_vline(xintercept = vline_years, color = "black", linetype = "dashed", size = 0.7) +
 theme_minimal() +
  labs(title = 'År: {frame_time}') +
  transition_reveal(År)
  
```
```{r}
animate(p, fps = 10, duration = 5)
```

```{r}
data_1973 <- Kandidat_long %>% filter(År == 1973)

ggplot(data_1973, aes(x = Parti, y = Mandater)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(title = "Folketingsvalg 1973 - Mandatfordeling",
       x = "Parti", y = "Antal mandater") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}

```

```{r}
data_1977 <- Kandidat_long %>% filter(År == 1977)

ggplot(data_1977, aes(x = Parti, y = Mandater)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(title = "Folketingsvalg 1977 - Mandatfordeling",
       x = "Parti", y = "Antal mandater") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
data_1984 <- Kandidat_long %>% filter(År == 1984)

ggplot(data_1984, aes(x = Parti, y = Mandater)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(title = "Folketingsvalg 1984 - Mandatfordeling",
       x = "Parti", y = "Antal mandater") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
data_1994 <- Kandidat_long %>% filter(År == 1994)

ggplot(data_1994, aes(x = Parti, y = Mandater)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(title = "Folketingsvalg 1994 - Mandatfordeling",
       x = "Parti", y = "Antal mandater") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
data_2001 <- Kandidat_long %>% filter(År == 2001)

ggplot(data_1977, aes(x = Parti, y = Mandater)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  labs(title = "Folketingsvalg 2001 - Mandatfordeling",
       x = "Parti", y = "Antal mandater") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

